[package]
name = "skat-solver"
version = "0.1.0"
edition = "2021"


[dependencies]
arrayvec = "0.7.4"
fxhash = "0.2.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
